# -*- coding: utf-8 -*-
"""03112024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10T1_EPw8YJHKIxiv6I_rmv19Eua3Tk1v
"""

a = eval(input('Enter a number: '))
if a>0:
  print(a,'is greater than 0')
else:
  print(a,'is less than 0')
print('Over')

a = eval(input('Enter a number: '))
if a>0:
  print(a,'is greater than 0')
else:
  print(a,'is less than 0')
print('Over')