# -*- coding: utf-8 -*-
"""20240506

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eeN9OHyyImexz5J4ADeOq6V6q9VYnSQE
"""

import random
while True:
  for i in range(1,7):
    randNum = random.randint(1,49)
    print(randNum,end = ' ')
  print( )
  again = eval(input('continue:1 or quit:0---->'))
  if again == 0:
    break
print('Over')

import random
n1 = random.randint(1,100)
n2 = random.randint(1,100)
while True:
  solution = n1 + n2
  answer = eval(input('%d + %d = '%(n1,n2)))
  if answer == solution:
    print('Correct,you are very good.')
    break
  else:
    print('Wrong answer,try again.')
print('Over')

import random
n1 = random.randint(1,100)
n2 = random.randint(1,100)
while False:
  solution = n1 + n2
  answer = eval(input('%d + %d = '%(n1,n2)))
  if answer == solution:
    print('Correct,you are very good.')
    break
  else:
    print('Wrong answer,try again.')
print('Over')

total = 0
number = 1
while number <= 15:
  if number %5 == 0:
    number = number + 1
    continue
  print('%3d'%(number),end = ' ')
  total += number
  number += 1

print('\ntotal = %d'%(total))