# -*- coding: utf-8 -*-
"""20240226.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRNIdvPVFE8VlxJv7lR-XGR1OPSZIGh7
"""



a = 123
b = 123.456
c = 'Python'

#print(a)
#print(b)
#print(c)

#print('a=',a)
#print('b=',b)
#print('c=',c)

#print(a, end = ' ')
#print(b, end = ' ')
#print(c, end = ' ')

print(format(a,'5d'))
print(format(b,'10.2f'))
print(format(c,'10s'))
print()

#print(format(a,'<5d'))
#print(format(b,'>10.2f'))
#print(format(c,'>10s'))

print('|%5d|'%a)
print('|%10.2f|'%b)
print('|%10s|'%c)
print('|%-10s|'%c)

print(format(a,'5d'))
print(format(a,'5x'))
print(format(a,'5o'))
print(format(a,'5b'))

x=123
y=123456
z=12

print(format(x,'8d'),format(y,'8d'),format(z,'8d'))
print('%8d'%x,'%8d'%y,'%8d'%z)