# -*- coding: utf-8 -*-
"""2024.3.4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-GgS-4w8D4VWO9hdyuV4dZv7dyghnw-c
"""

print('Python\"lijun')
print('Python\'Lijun')
print('Python\\ lijun')
print('Python\tLijun')
print('Python\nLijun')

s=input()
print(s)
a=input('Enter a number: ')
print(a)

a=eval(input('Enter a number:'))
a=a+100
print(a)

a=int(input("Enter a number:"))
a=a+10
print(a)

a,b=eval(input('Enter two number:'))
print('a=%d,b=%d'%(a,b))

a=100
b=a/3
print(b)
c=a//3
print(c)
d=a**2
print(d)
e=a**0.5
print(e)
f=a%3
print(f)

a, b, c, d, e, f, g=eval(input('Enter 7 number:'))
a=a+2
b=b-2
c=c*2
d=d/3
e=e//3
f=f%3
g=g**2
print(a, b, c, d, e, f, g)

(area=(3.14159*r**2))
r=0
print(area)

area=3.14159*r**2

perimeter=2*3.14159*r

