# -*- coding: utf-8 -*-
"""2024.3.4 1-0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O-S8xRFuhkeDAHA5GAkRUnFY4mOn6U3A
"""

area=72.69017017488385

print('Python\"lijun')
print('Python\'Lijun')
print('Python\\ lijun')
print('Python\tLijun')
print('Python\nLijun')

s=input()
print(s)
a=input('Enter a number: ')
print(a)

a=eval(input('Enter a number:'))
a=a+100
print(a)

a=int(input("Enter a number:"))
a=a+10
print(a)

a,b=eval(input('Enter two number:'))
print('a=%d,b=%d'%(a,b))

a=100
b=a/3
print(b)
c=a//3
print(c)
d=a**2
print(d)
e=a**0.5
print(e)
f=a%3
print(f)

a, b, c, d, e, f, g=eval(input('Enter 7 number:'))
a=a+2
b=b-2
c=c*2
d=d/3
e=e//3
f=f%3
g=g**2
print(a, b, c, d, e, f, g)

area=3.14159*r**2
print(area)

perimeter=2*3.14159*r
print(perimeter)

import math
math.pi
print(math.pi)

math.e
print(math.e)

area=3.14159*r**2
print(area)

perimeter=2*3.14159*r
print(perimeter)

import math
area=math.pi*r**2
print(area)

perimeter=2*math.pi*r
print(perimeter)



import math
math.sin(0)

math.sin(math.pi/2)

math.cos(math.pi/2)

import math
s=6.5
area=(5*s**2)/(4*math.tan(math.pi/5))
print(area)

import math
s=6.5
n=5
area=(n*s**2)/(4*math.tan(math.pi/n))
print(area)

a=('abs(-100)')
print(a)
b=max(22,33,11,88,99,66)
print(b)

c=min(22,33,11,88,99,66)
print(c)

d=(pow(2,10))
print(d)

e=(round(5.6))
print(e)

f=(round(5.2))
print(f)

g=(round(4.6))
print(g)

h=(round(4.5))
print(h)

i=(round(123.456,2))
print(i)

j=(round(123.456,1))
print(j)