# -*- coding: utf-8 -*-
"""2024.03.25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gm9pXajrmu8IXpcn_P08ZQTK4p1MmVZ6
"""

i=1
 total=0
 while i <=100:
  total +=i
  i+=1
print('total=',total)

i=2
total=0
while i<=100:
  total+=i
  i+=1
print('total=',total)

total=0
for i in range(1,100):
  total+=i
print('total=',total)

i=1
total=0
while i<=100:
  total+=i
  i+=2
print('total=',total)